spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 300 # amount of simultaneous connections
      minimum-idle: 10 # amount of ready connections
      connection-timeout: 20000 # waiting time before error
      max-lifetime: 1800000 # maximum lifetime of a connection in the pool (30 minutes).
      pool-name: GameHikariPool # Name for monitoring

  jpa:
    show-sql: false
    open-in-view: false
    hibernate:
      ddl-auto: validate
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate:
        # optimization: group multiple INSERT/UPDATE statements into single network packets.
        jdbc:
          batch_size: 50
          order_inserts: true
          order_updates: true
        # disable formatting to save CPU cycles
        format_sql: false